import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { Model } from '../models/Model.js';
import { AdminUser } from '../models/AdminUser.js';
import { AdminEmail } from '../models/AdminEmail.js';
import { UserFallbackConfig } from '../models/UserFallbackConfig.js';
import { hashPassword } from '../lib/crypto.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SQLITE_PATH = path.resolve(__dirname, '../../data/OmniKeyAI.db');

export async function seedMongoModels(): Promise<void> {
  try {
    let sqliteModels: any[] = [];

    // 1. Attempt to extract models from local SQLite database to preserve any custom changes
    if (fs.existsSync(SQLITE_PATH)) {
      console.log(`Found local SQLite database at ${SQLITE_PATH}. Extracting models catalog...`);
      try {
        const db = new Database(SQLITE_PATH, { readonly: true });
        sqliteModels = db.prepare('SELECT * FROM models').all();
        db.close();
        console.log(`Successfully extracted ${sqliteModels.length} models from SQLite.`);
      } catch (err) {
        console.warn('Failed to query SQLite database. Falling back to default seeding...', err);
      }
    } else {
      console.log('No local SQLite database found. Seeding default models catalog...');
    }

    // 2. Fallback to default catalog if SQLite is not present or failed to read
    if (sqliteModels.length === 0) {
      sqliteModels = getDefaultModels();
      console.log(`Using default catalog of ${sqliteModels.length} models for seeding.`);
    }

    // Ensure virtual promo model is present in the source list for MongoDB seeding
    const hasPromoModel = sqliteModels.some(m => m.platform === 'omnikey' && (m.model_id === 'omnikey-promo' || m.modelId === 'omnikey-promo'));
    if (!hasPromoModel) {
      sqliteModels.push({
        id: 9999,
        platform: 'omnikey',
        model_id: 'omnikey-promo',
        display_name: 'Promo Model',
        intelligence_rank: 5,
        speed_rank: 5,
        size_label: 'OmniKey',
        rpm_limit: null,
        rpd_limit: null,
        tpm_limit: null,
        tpd_limit: null,
        monthly_token_budget: '10M',
        context_window: 128000,
        enabled: 1
      });
    }

    // 3. Reconcile MongoDB models with the source models catalog
    let addedCount = 0;
    let updatedCount = 0;
    let disabledOrDeletedCount = 0;

    const sourceKeys = new Set<string>();

    for (const m of sqliteModels) {
      const platform = m.platform;
      const modelId = m.model_id || m.modelId;
      const displayName = m.display_name || m.displayName;
      const intelligenceRank = Number(m.intelligence_rank || m.intelligenceRank);
      const speedRank = Number(m.speed_rank || m.speedRank);
      const sizeLabel = m.size_label || m.sizeLabel || '';
      const rpmLimit = m.rpm_limit !== undefined ? m.rpm_limit : m.rpmLimit;
      const rpdLimit = m.rpd_limit !== undefined ? m.rpd_limit : m.rpdLimit;
      const tpmLimit = m.tpm_limit !== undefined ? m.tpm_limit : m.tpmLimit;
      const tpdLimit = m.tpd_limit !== undefined ? m.tpd_limit : m.tpdLimit;
      const monthlyTokenBudget = m.monthly_token_budget || m.monthlyTokenBudget || '';
      const contextWindow = m.context_window !== undefined ? m.context_window : m.contextWindow;
      const enabled = m.enabled === 1 || m.enabled === true;

      sourceKeys.add(`${platform}:${modelId}`);

      const existing = await Model.findOne({ platform, modelId });

      if (existing) {
        // Check for updates
        let isChanged = false;
        if (existing.displayName !== displayName) { existing.displayName = displayName; isChanged = true; }
        if (existing.intelligenceRank !== intelligenceRank) { existing.intelligenceRank = intelligenceRank; isChanged = true; }
        if (existing.speedRank !== speedRank) { existing.speedRank = speedRank; isChanged = true; }
        if (existing.sizeLabel !== sizeLabel) { existing.sizeLabel = sizeLabel; isChanged = true; }
        if (existing.rpmLimit !== rpmLimit) { existing.rpmLimit = rpmLimit; isChanged = true; }
        if (existing.rpdLimit !== rpdLimit) { existing.rpdLimit = rpdLimit; isChanged = true; }
        if (existing.tpmLimit !== tpmLimit) { existing.tpmLimit = tpmLimit; isChanged = true; }
        if (existing.tpdLimit !== tpdLimit) { existing.tpdLimit = tpdLimit; isChanged = true; }
        if (existing.monthlyTokenBudget !== monthlyTokenBudget) { existing.monthlyTokenBudget = monthlyTokenBudget; isChanged = true; }
        if (existing.contextWindow !== contextWindow) { existing.contextWindow = contextWindow; isChanged = true; }
        if (existing.enabled !== enabled) {
          existing.enabled = enabled;
          isChanged = true;
          if (!enabled) {
            // Disable by default for all users if globally disabled
            await UserFallbackConfig.updateMany({ modelId: existing._id }, { $set: { enabled: false } });
          }
        }

        if (isChanged) {
          await existing.save();
          updatedCount++;
        }
      } else {
        // Create new model
        await Model.create({
          platform,
          modelId,
          displayName,
          intelligenceRank,
          speedRank,
          sizeLabel,
          rpmLimit,
          rpdLimit,
          tpmLimit,
          tpdLimit,
          monthlyTokenBudget,
          contextWindow,
          enabled
        });
        addedCount++;
      }
    }

    // 4. Disable or remove models in MongoDB that are no longer in SQLite/source catalog
    const allMongoModels = await Model.find();
    for (const mm of allMongoModels) {
      const key = `${mm.platform}:${mm.modelId}`;
      if (!sourceKeys.has(key)) {
        // If it was present in Mongo but not in SQLite source, delete it to keep catalogs in exact sync
        await Model.deleteOne({ _id: mm._id });
        disabledOrDeletedCount++;
      }
    }

    console.log(`MongoDB catalog synchronization complete. Added: ${addedCount}, Updated: ${updatedCount}, Removed: ${disabledOrDeletedCount}.`);
  } catch (error) {
    console.error('Error during MongoDB model catalog synchronization:', error);
  }
}

function getDefaultModels() {
  return [
  {
    "id": 1,
    "platform": "google",
    "model_id": "gemini-2.5-pro",
    "display_name": "Gemini 2.5 Pro",
    "intelligence_rank": 14,
    "speed_rank": 8,
    "size_label": "Frontier",
    "rpm_limit": 5,
    "rpd_limit": 50,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 1048576,
    "enabled": 0
  },
  {
    "id": 2,
    "platform": "google",
    "model_id": "gemini-2.5-flash",
    "display_name": "Gemini 2.5 Flash",
    "intelligence_rank": 20,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 10,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 3,
    "platform": "google",
    "model_id": "gemini-2.5-flash-lite",
    "display_name": "Gemini 2.5 Flash-Lite",
    "intelligence_rank": 26,
    "speed_rank": 3,
    "size_label": "Medium",
    "rpm_limit": 15,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 6,
    "platform": "openrouter",
    "model_id": "qwen/qwen3-coder:free",
    "display_name": "Qwen3 Coder (free)",
    "intelligence_rank": 2,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 7,
    "platform": "openrouter",
    "model_id": "z-ai/glm-4.5-air:free",
    "display_name": "GLM-4.5 Air (free)",
    "intelligence_rank": 8,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 10,
    "platform": "cerebras",
    "model_id": "qwen-3-235b-a22b-instruct-2507",
    "display_name": "Qwen3 235B",
    "intelligence_rank": 6,
    "speed_rank": 1,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 2400,
    "tpm_limit": 30000,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 8192,
    "enabled": 0
  },
  {
    "id": 12,
    "platform": "github",
    "model_id": "gpt-4o",
    "display_name": "GPT-4o",
    "intelligence_rank": 25,
    "speed_rank": 7,
    "size_label": "Large",
    "rpm_limit": 10,
    "rpd_limit": 50,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18M",
    "context_window": 8000,
    "enabled": 1
  },
  {
    "id": 13,
    "platform": "sambanova",
    "model_id": "Meta-Llama-3.3-70B-Instruct",
    "display_name": "Llama 3.3 70B",
    "intelligence_rank": 17,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~6M",
    "context_window": 8192,
    "enabled": 1
  },
  {
    "id": 14,
    "platform": "mistral",
    "model_id": "mistral-large-latest",
    "display_name": "Mistral Large 3",
    "intelligence_rank": 14,
    "speed_rank": 8,
    "size_label": "Large",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 15,
    "platform": "mistral",
    "model_id": "magistral-medium-latest",
    "display_name": "Magistral Medium",
    "intelligence_rank": 21,
    "speed_rank": 8,
    "size_label": "Large",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 16,
    "platform": "mistral",
    "model_id": "codestral-latest",
    "display_name": "Codestral",
    "intelligence_rank": 16,
    "speed_rank": 6,
    "size_label": "Medium",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 256000,
    "enabled": 1
  },
  {
    "id": 17,
    "platform": "groq",
    "model_id": "llama-3.3-70b-versatile",
    "display_name": "Llama 3.3 70B",
    "intelligence_rank": 17,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 30,
    "rpd_limit": 1000,
    "tpm_limit": 12000,
    "tpd_limit": 100000,
    "monthly_token_budget": "~15M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 18,
    "platform": "groq",
    "model_id": "meta-llama/llama-4-scout-17b-16e-instruct",
    "display_name": "Llama 4 Scout",
    "intelligence_rank": 12,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 30,
    "rpd_limit": 1000,
    "tpm_limit": 30000,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 19,
    "platform": "nvidia",
    "model_id": "meta/llama-3.1-70b-instruct",
    "display_name": "Llama 3.1 70B (NV)",
    "intelligence_rank": 17,
    "speed_rank": 6,
    "size_label": "Large",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (1k credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 20,
    "platform": "cohere",
    "model_id": "command-r-plus-08-2024",
    "display_name": "Command R+ (08-2024)",
    "intelligence_rank": 27,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 33,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-2M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 21,
    "platform": "cloudflare",
    "model_id": "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    "display_name": "Llama 3.3 70B fp8-fast (CF)",
    "intelligence_rank": 17,
    "speed_rank": 11,
    "size_label": "Medium",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18-45M",
    "context_window": 24000,
    "enabled": 1
  },
  {
    "id": 23,
    "platform": "zhipu",
    "model_id": "glm-4.5-flash",
    "display_name": "GLM-4.5 Flash",
    "intelligence_rank": 24,
    "speed_rank": 4,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 38,
    "platform": "openrouter",
    "model_id": "nvidia/nemotron-3-super-120b-a12b:free",
    "display_name": "Nemotron 3 Super 120B (free)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 1000000,
    "enabled": 1
  },
  {
    "id": 39,
    "platform": "openrouter",
    "model_id": "qwen/qwen3-next-80b-a3b-instruct:free",
    "display_name": "Qwen3-Next 80B (free)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 40,
    "platform": "openrouter",
    "model_id": "minimax/minimax-m2.5:free",
    "display_name": "MiniMax M2.5 (free)",
    "intelligence_rank": 1,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 196608,
    "enabled": 1
  },
  {
    "id": 44,
    "platform": "openrouter",
    "model_id": "nvidia/nemotron-3-nano-30b-a3b:free",
    "display_name": "Nemotron 3 Nano 30B (free)",
    "intelligence_rank": 23,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 45,
    "platform": "openrouter",
    "model_id": "openai/gpt-oss-120b:free",
    "display_name": "GPT-OSS 120B (free)",
    "intelligence_rank": 6,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 46,
    "platform": "openrouter",
    "model_id": "openai/gpt-oss-20b:free",
    "display_name": "GPT-OSS 20B (free)",
    "intelligence_rank": 18,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 47,
    "platform": "openrouter",
    "model_id": "meta-llama/llama-3.3-70b-instruct:free",
    "display_name": "Llama 3.3 70B (free)",
    "intelligence_rank": 17,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 48,
    "platform": "sambanova",
    "model_id": "DeepSeek-V3.1",
    "display_name": "DeepSeek V3.1",
    "intelligence_rank": 5,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~3M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 49,
    "platform": "sambanova",
    "model_id": "DeepSeek-V3.2",
    "display_name": "DeepSeek V3.2",
    "intelligence_rank": 4,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~3M",
    "context_window": 32768,
    "enabled": 1
  },
  {
    "id": 50,
    "platform": "sambanova",
    "model_id": "Llama-4-Maverick-17B-128E-Instruct",
    "display_name": "Llama 4 Maverick",
    "intelligence_rank": 11,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~3M",
    "context_window": 8192,
    "enabled": 1
  },
  {
    "id": 51,
    "platform": "sambanova",
    "model_id": "gpt-oss-120b",
    "display_name": "GPT-OSS 120B (SambaNova)",
    "intelligence_rank": 6,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~3M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 52,
    "platform": "groq",
    "model_id": "openai/gpt-oss-120b",
    "display_name": "GPT-OSS 120B (Groq)",
    "intelligence_rank": 6,
    "speed_rank": 2,
    "size_label": "Large",
    "rpm_limit": 30,
    "rpd_limit": 1000,
    "tpm_limit": 8000,
    "tpd_limit": 200000,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 53,
    "platform": "groq",
    "model_id": "openai/gpt-oss-20b",
    "display_name": "GPT-OSS 20B (Groq)",
    "intelligence_rank": 18,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 30,
    "rpd_limit": 1000,
    "tpm_limit": 8000,
    "tpd_limit": 200000,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 54,
    "platform": "groq",
    "model_id": "qwen/qwen3-32b",
    "display_name": "Qwen3 32B (Groq)",
    "intelligence_rank": 19,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 60,
    "rpd_limit": 1000,
    "tpm_limit": 6000,
    "tpd_limit": 500000,
    "monthly_token_budget": "~15M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 55,
    "platform": "groq",
    "model_id": "llama-3.1-8b-instant",
    "display_name": "Llama 3.1 8B Instant",
    "intelligence_rank": 28,
    "speed_rank": 2,
    "size_label": "Small",
    "rpm_limit": 30,
    "rpd_limit": 14400,
    "tpm_limit": 6000,
    "tpd_limit": 500000,
    "monthly_token_budget": "~15M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 56,
    "platform": "mistral",
    "model_id": "devstral-latest",
    "display_name": "Devstral",
    "intelligence_rank": 16,
    "speed_rank": 8,
    "size_label": "Medium",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 57,
    "platform": "mistral",
    "model_id": "mistral-medium-latest",
    "display_name": "Mistral Medium 3.5",
    "intelligence_rank": 14,
    "speed_rank": 8,
    "size_label": "Large",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 58,
    "platform": "github",
    "model_id": "openai/gpt-4.1",
    "display_name": "GPT-4.1 (GitHub)",
    "intelligence_rank": 20,
    "speed_rank": 7,
    "size_label": "Large",
    "rpm_limit": 10,
    "rpd_limit": 50,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~9M",
    "context_window": 128000,
    "enabled": 1
  },
  {
    "id": 59,
    "platform": "cohere",
    "model_id": "command-a-03-2025",
    "display_name": "Command-A (03-2025)",
    "intelligence_rank": 27,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 33,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-2M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 60,
    "platform": "cloudflare",
    "model_id": "@cf/openai/gpt-oss-120b",
    "display_name": "GPT-OSS 120B (CF)",
    "intelligence_rank": 6,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18-45M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 61,
    "platform": "cloudflare",
    "model_id": "@cf/zai-org/glm-4.7-flash",
    "display_name": "GLM-4.7 Flash (CF)",
    "intelligence_rank": 10,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18-45M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 62,
    "platform": "cloudflare",
    "model_id": "@cf/meta/llama-4-scout-17b-16e-instruct",
    "display_name": "Llama 4 Scout (CF)",
    "intelligence_rank": 12,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18-45M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 63,
    "platform": "cerebras",
    "model_id": "zai-glm-4.7",
    "display_name": "GLM-4.7 (Cerebras)",
    "intelligence_rank": 7,
    "speed_rank": 1,
    "size_label": "Frontier",
    "rpm_limit": 10,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 8192,
    "enabled": 0
  },
  {
    "id": 65,
    "platform": "cloudflare",
    "model_id": "@cf/qwen/qwen3-30b-a3b-fp8",
    "display_name": "Qwen3 30B-A3B fp8 (CF)",
    "intelligence_rank": 7,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~18-45M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 66,
    "platform": "cloudflare",
    "model_id": "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    "display_name": "DeepSeek R1 Distill Qwen 32B (CF)",
    "intelligence_rank": 9,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3-5M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 67,
    "platform": "google",
    "model_id": "gemini-3.1-flash-lite-preview",
    "display_name": "Gemini 3.1 Flash-Lite Preview",
    "intelligence_rank": 18,
    "speed_rank": 3,
    "size_label": "Medium",
    "rpm_limit": 15,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 68,
    "platform": "google",
    "model_id": "gemini-3-flash-preview",
    "display_name": "Gemini 3 Flash Preview",
    "intelligence_rank": 11,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 10,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 69,
    "platform": "google",
    "model_id": "gemini-3.1-pro-preview",
    "display_name": "Gemini 3.1 Pro Preview",
    "intelligence_rank": 1,
    "speed_rank": 8,
    "size_label": "Frontier",
    "rpm_limit": 5,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 0
  },
  {
    "id": 71,
    "platform": "openrouter",
    "model_id": "liquid/lfm-2.5-1.2b-instruct:free",
    "display_name": "Liquid LFM 2.5 1.2B (free)",
    "intelligence_rank": 30,
    "speed_rank": 10,
    "size_label": "Small",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 32768,
    "enabled": 1
  },
  {
    "id": 74,
    "platform": "openrouter",
    "model_id": "poolside/laguna-m.1:free",
    "display_name": "Poolside Laguna M.1 (free)",
    "intelligence_rank": 13,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 75,
    "platform": "openrouter",
    "model_id": "google/gemma-4-26b-a4b-it:free",
    "display_name": "Gemma 4 26B-A4B (free)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 76,
    "platform": "openrouter",
    "model_id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "display_name": "Nemotron 3 Nano 30B Reasoning (free)",
    "intelligence_rank": 23,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 77,
    "platform": "openrouter",
    "model_id": "poolside/laguna-xs.2:free",
    "display_name": "Poolside Laguna XS.2 (free)",
    "intelligence_rank": 26,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 78,
    "platform": "openrouter",
    "model_id": "nvidia/nemotron-nano-9b-v2:free",
    "display_name": "Nemotron Nano 9B v2 (free)",
    "intelligence_rank": 28,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 128000,
    "enabled": 1
  },
  {
    "id": 79,
    "platform": "openrouter",
    "model_id": "liquid/lfm-2.5-1.2b-thinking:free",
    "display_name": "Liquid LFM 2.5 1.2B Thinking (free)",
    "intelligence_rank": 30,
    "speed_rank": 10,
    "size_label": "Small",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 32768,
    "enabled": 1
  },
  {
    "id": 80,
    "platform": "zhipu",
    "model_id": "glm-4.7-flash",
    "display_name": "GLM-4.7 Flash",
    "intelligence_rank": 18,
    "speed_rank": 4,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 82,
    "platform": "sambanova",
    "model_id": "gemma-3-12b-it",
    "display_name": "Gemma 3 12B (SambaNova)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 20,
    "tpm_limit": null,
    "tpd_limit": 200000,
    "monthly_token_budget": "~3M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 83,
    "platform": "cloudflare",
    "model_id": "@cf/moonshotai/kimi-k2.6",
    "display_name": "Kimi K2.6 (CF)",
    "intelligence_rank": 2,
    "speed_rank": 11,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~10-20M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 84,
    "platform": "cloudflare",
    "model_id": "@cf/ibm-granite/granite-4.0-h-micro",
    "display_name": "Granite 4.0 H Micro (CF)",
    "intelligence_rank": 29,
    "speed_rank": 11,
    "size_label": "Small",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 85,
    "platform": "ollama",
    "model_id": "qwen3-coder:480b",
    "display_name": "Qwen3-Coder 480B (Ollama)",
    "intelligence_rank": 2,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 86,
    "platform": "ollama",
    "model_id": "mistral-large-3:675b",
    "display_name": "Mistral Large 3 675B (Ollama)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 0
  },
  {
    "id": 87,
    "platform": "ollama",
    "model_id": "deepseek-v3.2",
    "display_name": "DeepSeek V3.2 (Ollama)",
    "intelligence_rank": 4,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 0
  },
  {
    "id": 88,
    "platform": "ollama",
    "model_id": "cogito-2.1:671b",
    "display_name": "Cogito 2.1 671B (Ollama)",
    "intelligence_rank": 4,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 89,
    "platform": "ollama",
    "model_id": "kimi-k2-thinking",
    "display_name": "Kimi K2 Thinking (Ollama)",
    "intelligence_rank": 5,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 0
  },
  {
    "id": 90,
    "platform": "ollama",
    "model_id": "glm-4.7",
    "display_name": "GLM-4.7 (Ollama)",
    "intelligence_rank": 6,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 91,
    "platform": "ollama",
    "model_id": "gpt-oss:120b",
    "display_name": "GPT-OSS 120B (Ollama)",
    "intelligence_rank": 6,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~10-20M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 92,
    "platform": "ollama",
    "model_id": "devstral-2:123b",
    "display_name": "Devstral 2 123B (Ollama)",
    "intelligence_rank": 8,
    "speed_rank": 10,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~10-20M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 93,
    "platform": "ollama",
    "model_id": "gpt-oss:20b",
    "display_name": "GPT-OSS 20B (Ollama)",
    "intelligence_rank": 18,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~20-30M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 94,
    "platform": "ollama",
    "model_id": "gemma4:31b",
    "display_name": "Gemma 4 31B (Ollama)",
    "intelligence_rank": 22,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~20-30M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 95,
    "platform": "nvidia",
    "model_id": "meta/llama-3.3-70b-instruct",
    "display_name": "Llama 3.3 70B (NV)",
    "intelligence_rank": 17,
    "speed_rank": 6,
    "size_label": "Large",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 96,
    "platform": "nvidia",
    "model_id": "meta/llama-4-maverick-17b-128e-instruct",
    "display_name": "Llama 4 Maverick (NV)",
    "intelligence_rank": 11,
    "speed_rank": 6,
    "size_label": "Large",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 97,
    "platform": "nvidia",
    "model_id": "deepseek-ai/deepseek-v4-pro",
    "display_name": "DeepSeek V4 Pro (NV)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 98,
    "platform": "nvidia",
    "model_id": "mistralai/mistral-large-3-675b-instruct-2512",
    "display_name": "Mistral Large 3 675B (NV)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 99,
    "platform": "nvidia",
    "model_id": "minimaxai/minimax-m2.7",
    "display_name": "MiniMax M2.7 (NV)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2M (credits)",
    "context_window": 196608,
    "enabled": 1
  },
  {
    "id": 100,
    "platform": "nvidia",
    "model_id": "nvidia/nemotron-3-super-120b-a12b",
    "display_name": "Nemotron 3 Super 120B (NV)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2M (credits)",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 101,
    "platform": "nvidia",
    "model_id": "nvidia/nemotron-3-nano-30b-a3b",
    "display_name": "Nemotron 3 Nano 30B (NV)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 102,
    "platform": "nvidia",
    "model_id": "google/gemma-4-31b-it",
    "display_name": "Gemma 4 31B (NV)",
    "intelligence_rank": 19,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 103,
    "platform": "nvidia",
    "model_id": "moonshotai/kimi-k2.6",
    "display_name": "Kimi K2.6 (NV)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 105,
    "platform": "cerebras",
    "model_id": "llama3.1-8b",
    "display_name": "Llama 3.1 8B (Cerebras)",
    "intelligence_rank": 28,
    "speed_rank": 1,
    "size_label": "Small",
    "rpm_limit": 5,
    "rpd_limit": 2400,
    "tpm_limit": 30000,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 131072,
    "enabled": 0
  },
  {
    "id": 106,
    "platform": "groq",
    "model_id": "groq/compound",
    "display_name": "Compound (Groq)",
    "intelligence_rank": 6,
    "speed_rank": 2,
    "size_label": "Large",
    "rpm_limit": 30,
    "rpd_limit": 250,
    "tpm_limit": 70000,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 107,
    "platform": "groq",
    "model_id": "groq/compound-mini",
    "display_name": "Compound Mini (Groq)",
    "intelligence_rank": 18,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 30,
    "rpd_limit": 250,
    "tpm_limit": 70000,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 108,
    "platform": "kilo",
    "model_id": "nvidia/nemotron-3-super-120b-a12b:free",
    "display_name": "Nemotron 3 Super 120B (Kilo)",
    "intelligence_rank": 22,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (200/hr)",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 109,
    "platform": "pollinations",
    "model_id": "openai-fast",
    "display_name": "GPT-OSS 20B (Pollinations)",
    "intelligence_rank": 18,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~? (anon)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 110,
    "platform": "llm7",
    "model_id": "gpt-oss-20b",
    "display_name": "GPT-OSS 20B (LLM7)",
    "intelligence_rank": 18,
    "speed_rank": 10,
    "size_label": "Medium",
    "rpm_limit": 100,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (100/hr)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 111,
    "platform": "llm7",
    "model_id": "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
    "display_name": "Llama 3.1 8B Turbo (LLM7)",
    "intelligence_rank": 28,
    "speed_rank": 10,
    "size_label": "Small",
    "rpm_limit": 100,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (100/hr)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 112,
    "platform": "llm7",
    "model_id": "codestral-latest",
    "display_name": "Codestral (LLM7)",
    "intelligence_rank": 16,
    "speed_rank": 8,
    "size_label": "Medium",
    "rpm_limit": 100,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (100/hr)",
    "context_window": 32000,
    "enabled": 1
  },
  {
    "id": 113,
    "platform": "llm7",
    "model_id": "ministral-8b-2512",
    "display_name": "Ministral 8B (LLM7)",
    "intelligence_rank": 28,
    "speed_rank": 10,
    "size_label": "Small",
    "rpm_limit": 100,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (100/hr)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 114,
    "platform": "llm7",
    "model_id": "GLM-4.6V-Flash",
    "display_name": "GLM-4.6V Flash (LLM7)",
    "intelligence_rank": 15,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 100,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~2-3M (100/hr)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 115,
    "platform": "openrouter",
    "model_id": "arcee-ai/trinity-large-thinking:free",
    "display_name": "Trinity Large Thinking (free)",
    "intelligence_rank": 5,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 116,
    "platform": "openrouter",
    "model_id": "baidu/cobuddy:free",
    "display_name": "CoBuddy (free)",
    "intelligence_rank": 6,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 117,
    "platform": "openrouter",
    "model_id": "openrouter/owl-alpha",
    "display_name": "Owl Alpha (OR-house)",
    "intelligence_rank": 5,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 118,
    "platform": "openrouter",
    "model_id": "nousresearch/hermes-3-llama-3.1-405b:free",
    "display_name": "Hermes 3 405B (free)",
    "intelligence_rank": 17,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 119,
    "platform": "groq",
    "model_id": "openai/gpt-oss-safeguard-20b",
    "display_name": "GPT-OSS Safeguard 20B (Groq)",
    "intelligence_rank": 18,
    "speed_rank": 2,
    "size_label": "Medium",
    "rpm_limit": 30,
    "rpd_limit": 1000,
    "tpm_limit": 8000,
    "tpd_limit": 200000,
    "monthly_token_budget": "~6M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 120,
    "platform": "cloudflare",
    "model_id": "@cf/nvidia/nemotron-3-120b-a12b",
    "display_name": "Nemotron 3 120B (CF)",
    "intelligence_rank": 9,
    "speed_rank": 11,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~5-10M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 121,
    "platform": "cloudflare",
    "model_id": "@cf/google/gemma-4-26b-a4b-it",
    "display_name": "Gemma 4 26B-A4B it (CF)",
    "intelligence_rank": 22,
    "speed_rank": 11,
    "size_label": "Medium",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~10-20M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 122,
    "platform": "google",
    "model_id": "gemini-3.5-flash",
    "display_name": "Gemini 3.5 Flash",
    "intelligence_rank": 3,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 10,
    "rpd_limit": 20,
    "tpm_limit": 250000,
    "tpd_limit": null,
    "monthly_token_budget": "~3M",
    "context_window": 1048576,
    "enabled": 1
  },
  {
    "id": 123,
    "platform": "nvidia",
    "model_id": "deepseek-ai/deepseek-v4-flash",
    "display_name": "DeepSeek V4 Flash (NV)",
    "intelligence_rank": 4,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 124,
    "platform": "nvidia",
    "model_id": "z-ai/glm-5.1",
    "display_name": "GLM-5.1 (NV, slow cold-start)",
    "intelligence_rank": 5,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 200000,
    "enabled": 1
  },
  {
    "id": 125,
    "platform": "nvidia",
    "model_id": "qwen/qwen3-coder-480b-a35b-instruct",
    "display_name": "Qwen3-Coder 480B (NV)",
    "intelligence_rank": 2,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": 40,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~3M (credits)",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 126,
    "platform": "mistral",
    "model_id": "mistral-small-latest",
    "display_name": "Mistral Small 4",
    "intelligence_rank": 14,
    "speed_rank": 8,
    "size_label": "Medium",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 127,
    "platform": "mistral",
    "model_id": "ministral-8b-latest",
    "display_name": "Ministral 3 8B",
    "intelligence_rank": 28,
    "speed_rank": 8,
    "size_label": "Small",
    "rpm_limit": 2,
    "rpd_limit": null,
    "tpm_limit": 500000,
    "tpd_limit": null,
    "monthly_token_budget": "~50-100M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 128,
    "platform": "cohere",
    "model_id": "command-a-reasoning-08-2025",
    "display_name": "Command A Reasoning (08-2025)",
    "intelligence_rank": 13,
    "speed_rank": 11,
    "size_label": "Large",
    "rpm_limit": 20,
    "rpd_limit": 33,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-2M",
    "context_window": 256000,
    "enabled": 1
  },
  {
    "id": 129,
    "platform": "cohere",
    "model_id": "command-r-08-2024",
    "display_name": "Command R (08-2024)",
    "intelligence_rank": 25,
    "speed_rank": 11,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 33,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-2M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 130,
    "platform": "ollama",
    "model_id": "qwen3-coder-next",
    "display_name": "Qwen3-Coder Next (Ollama)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~10-20M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 131,
    "platform": "huggingface",
    "model_id": "deepseek-ai/DeepSeek-V4-Flash",
    "display_name": "DeepSeek V4 Flash (HF)",
    "intelligence_rank": 4,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-3M",
    "context_window": 131072,
    "enabled": 1
  },
  {
    "id": 132,
    "platform": "huggingface",
    "model_id": "moonshotai/Kimi-K2.6",
    "display_name": "Kimi K2.6 (HF)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Frontier",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-3M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 133,
    "platform": "huggingface",
    "model_id": "Qwen/Qwen3-Coder-Next",
    "display_name": "Qwen3-Coder Next (HF)",
    "intelligence_rank": 3,
    "speed_rank": 9,
    "size_label": "Large",
    "rpm_limit": null,
    "rpd_limit": null,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1-3M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 12274,
    "platform": "openrouter",
    "model_id": "google/gemma-4-31b-it:free",
    "display_name": "Gemma 4 31B (free)",
    "intelligence_rank": 19,
    "speed_rank": 9,
    "size_label": "Medium",
    "rpm_limit": 20,
    "rpd_limit": 200,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~6M",
    "context_window": 262144,
    "enabled": 1
  },
  {
    "id": 12308,
    "platform": "cerebras",
    "model_id": "gpt-oss-120b",
    "display_name": "GPT-OSS 120B (Cerebras)",
    "intelligence_rank": 6,
    "speed_rank": 1,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 2400,
    "tpm_limit": 30000,
    "tpd_limit": 1000000,
    "monthly_token_budget": "~30M",
    "context_window": 131072,
  },
  {
    "id": 16656,
    "platform": "google",
    "model_id": "imagen-3.0-generate-002",
    "display_name": "Imagen 3 (Google)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 0
  },
  {
    "id": 16657,
    "platform": "cloudflare",
    "model_id": "flux-1-schnell",
    "display_name": "Flux 1 Schnell (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17060,
    "platform": "cloudflare",
    "model_id": "flux-2-dev",
    "display_name": "Flux 2 Dev (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17061,
    "platform": "cloudflare",
    "model_id": "flux-2-klein-4b",
    "display_name": "Flux 2 Klein 4B (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17062,
    "platform": "cloudflare",
    "model_id": "flux-2-klein-9b",
    "display_name": "Flux 2 Klein 9B (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17063,
    "platform": "cloudflare",
    "model_id": "phoenix-1.0",
    "display_name": "Leonardo Phoenix 1.0 (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17064,
    "platform": "cloudflare",
    "model_id": "lucid-origin",
    "display_name": "Leonardo Lucid Origin (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17065,
    "platform": "cloudflare",
    "model_id": "stable-diffusion-xl-base-1.0",
    "display_name": "Stable Diffusion XL (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  },
  {
    "id": 17066,
    "platform": "cloudflare",
    "model_id": "dreamshaper-8-lcm",
    "display_name": "DreamShaper 8 LCM (Cloudflare)",
    "intelligence_rank": 5,
    "speed_rank": 5,
    "size_label": "Large",
    "rpm_limit": 5,
    "rpd_limit": 100,
    "tpm_limit": null,
    "tpd_limit": null,
    "monthly_token_budget": "~1.5M",
    "context_window": null,
    "enabled": 1
  }
];
}

export async function seedMongoAdmin(): Promise<void> {
  try {
    const existing = await AdminUser.findOne({ username: 'admin' });
    if (existing) {
      return;
    }

    const passwordHash = hashPassword('admin');
    await AdminUser.create({
      username: 'admin',
      passwordHash
    });
    console.log('[MongoDB] Seeded default admin account successfully.');
  } catch (err: any) {
    console.error('[MongoDB] Failed to seed admin account:', err.message || err);
  }
}

export async function seedMongoAdminEmails(): Promise<void> {
  try {
    const count = await AdminEmail.countDocuments();
    if (count > 0) {
      return;
    }

    await AdminEmail.create({
      email: 'harshit.soni.23cse@bmu.edu.in'
    });
    console.log('[MongoDB] Seeded default admin email successfully.');
  } catch (err: any) {
    console.error('[MongoDB] Failed to seed admin emails:', err.message || err);
  }
}

